# Generated by Django 5.2.2 on 2025-06-20 03:33

from __future__ import annotations

import colorfield.fields
import django.contrib.sites.models
import django.db.models.deletion
import openbook.core.models.mixins.file
import openbook.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Language Code')),
                ('name', models.CharField(max_length=64, verbose_name='Translated Name')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.site')),
                ('short_name', models.CharField(max_length=50, verbose_name='Short Name')),
                ('about_url', models.URLField(help_text='URL of your website with information for your users', verbose_name='Information Website')),
                ('brand_color', colorfield.fields.ColorField(default='#e2001a', image_field=None, max_length=25, samples=None, verbose_name='Brand Color')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
            },
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='HTMLLibrary',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('organization', models.CharField(max_length=100, validators=[openbook.core.validators.validate_library_name_part], verbose_name='Organization')),
                ('name', models.CharField(max_length=100, validators=[openbook.core.validators.validate_library_name_part], verbose_name='Name')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='Author')),
                ('license', models.CharField(blank=True, default='', max_length=50, verbose_name='License')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('coderepo', models.URLField(blank=True, default='', verbose_name='Code Repository')),
                ('bugtracker', models.URLField(blank=True, default='', verbose_name='Bug Tracker')),
                ('readme', models.TextField(blank=True, verbose_name='Read Me')),
                ('text_format', models.CharField(choices=[('TEXT', 'Plain Text'), ('HTML', 'HTML'), ('MD', 'Markdown')], default='MD', max_length=10, verbose_name='Text Format')),
                ('published', models.BooleanField(default=True, help_text='Allow other installations to download the library from this server', verbose_name='Published')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'HTML Library',
                'verbose_name_plural': 'HTML Libraries',
            },
        ),
        migrations.CreateModel(
            name='HTMLComponent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Tag Name')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='openbook_core.htmllibrary')),
            ],
            options={
                'verbose_name': 'HTML Component',
                'verbose_name_plural': 'HTML Components',
            },
        ),
        migrations.CreateModel(
            name='HTMLLibraryVersion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('file_data', models.FileField(blank=True, upload_to=openbook.core.models.mixins.file.FileUploadMixin._calc_file_path, verbose_name='File Data')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='File Name')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('mime_type', models.CharField(blank=True, max_length=64, verbose_name='MIME Type')),
                ('version', models.CharField(max_length=50, validators=[openbook.core.validators.validate_version_number], verbose_name='Version')),
                ('dependencies', models.JSONField(blank=True, default=None, null=True, verbose_name='Dependencies')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='openbook_core.htmllibrary')),
            ],
            options={
                'verbose_name': 'HTML Library Version',
                'verbose_name_plural': 'HTML Library Versions',
                'ordering': ['parent', '-version'],
            },
        ),
        migrations.CreateModel(
            name='HTMLComponentDefinition',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('definition', models.JSONField(blank=True, default=None, verbose_name='JSON Definition')),
                ('html_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='openbook_core.htmlcomponent')),
                ('library_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='openbook_core.htmllibraryversion')),
            ],
            options={
                'verbose_name': 'HTML Component Definition',
                'verbose_name_plural': 'HTML Component Definitions',
            },
        ),
        migrations.CreateModel(
            name='HTMLLibraryText',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('short_description', models.CharField(max_length=255, verbose_name='Short Description')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='openbook_core.htmllibrary')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_core.language')),
            ],
            options={
                'verbose_name': 'HTML Library Text',
                'verbose_name_plural': 'HTML Library Texts',
                'ordering': ('parent', 'language'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('file_data', models.FileField(blank=True, upload_to=openbook.core.models.mixins.file.FileUploadMixin._calc_file_path, verbose_name='File Data')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='File Name')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('mime_type', models.CharField(blank=True, max_length=64, verbose_name='MIME Type')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['content_type', 'object_id', 'file_name'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='htmllibrary',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_library_name'),
        ),
        migrations.AddConstraint(
            model_name='htmlcomponent',
            constraint=models.UniqueConstraint(fields=('library', 'tag_name'), name='unique_html_component'),
        ),
        migrations.AddConstraint(
            model_name='htmllibraryversion',
            constraint=models.UniqueConstraint(fields=('parent', 'version'), name='unique_library_version'),
        ),
        migrations.AddConstraint(
            model_name='htmlcomponentdefinition',
            constraint=models.UniqueConstraint(fields=('html_component', 'library_version'), name='unique_html_component_version'),
        ),
        migrations.AddIndex(
            model_name='htmllibrarytext',
            index=models.Index(fields=['parent', 'language'], name='openbook_co_parent__40589d_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['content_type', 'object_id', 'file_name'], name='openbook_co_content_4cc789_idx'),
        ),
    ]
