# Generated by Django 5.2.2 on 2025-06-20 13:40

from __future__ import annotations

import openbook.core.models.utils.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlcomponentdefinition',
            name='definition',
            field=models.JSONField(blank=True, default=None, encoder=openbook.core.models.utils.json.PrettyPrintJSONEncoder, verbose_name='JSON Definition'),
        ),
        migrations.AlterField(
            model_name='htmllibraryversion',
            name='dependencies',
            field=models.JSONField(blank=True, default=None, encoder=openbook.core.models.utils.json.PrettyPrintJSONEncoder, null=True, verbose_name='Dependencies'),
        ),
    ]
