/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CourseMaterial,
  PaginatedCourseMaterialList,
  PatchedCourseMaterial,
} from '../models/index';
import {
    CourseMaterialFromJSON,
    CourseMaterialToJSON,
    PaginatedCourseMaterialListFromJSON,
    PaginatedCourseMaterialListToJSON,
    PatchedCourseMaterialFromJSON,
    PatchedCourseMaterialToJSON,
} from '../models/index';

export interface ContentCourseMaterialsCreateRequest {
    courseMaterial: Omit<CourseMaterial, 'id'|'page_ranges'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentCourseMaterialsDestroyRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentCourseMaterialsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    course?: string;
    createdAt?: Date;
    createdAtGte?: Date;
    createdAtLte?: Date;
    createdBy?: string;
    modifiedAt?: Date;
    modifiedAtGte?: Date;
    modifiedAtLte?: Date;
    modifiedBy?: string;
    position?: number;
    positionGte?: number;
    positionLte?: number;
    textbook?: string;
}

export interface ContentCourseMaterialsPartialUpdateRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
    patchedCourseMaterial?: Omit<PatchedCourseMaterial, 'id'|'page_ranges'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
}

export interface ContentCourseMaterialsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentCourseMaterialsUpdateRequest {
    id: string;
    courseMaterial: Omit<CourseMaterial, 'id'|'page_ranges'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class CourseMaterialsApi extends runtime.BaseAPI {

    /**
     * Course Materials
     * Create
     */
    async contentCourseMaterialsCreateRaw(requestParameters: ContentCourseMaterialsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseMaterial>> {
        if (requestParameters['courseMaterial'] == null) {
            throw new runtime.RequiredError(
                'courseMaterial',
                'Required parameter "courseMaterial" was null or undefined when calling contentCourseMaterialsCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_materials/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CourseMaterialToJSON(requestParameters['courseMaterial']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseMaterialFromJSON(jsonValue));
    }

    /**
     * Course Materials
     * Create
     */
    async contentCourseMaterialsCreate(requestParameters: ContentCourseMaterialsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseMaterial> {
        const response = await this.contentCourseMaterialsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Course Materials
     * Delete
     */
    async contentCourseMaterialsDestroyRaw(requestParameters: ContentCourseMaterialsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentCourseMaterialsDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_materials/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Course Materials
     * Delete
     */
    async contentCourseMaterialsDestroy(requestParameters: ContentCourseMaterialsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.contentCourseMaterialsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Course Materials
     * List
     */
    async contentCourseMaterialsListRaw(requestParameters: ContentCourseMaterialsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedCourseMaterialList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['course'] != null) {
            queryParameters['course'] = requestParameters['course'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['created_at'] = (requestParameters['createdAt'] as any).toISOString();
        }

        if (requestParameters['createdAtGte'] != null) {
            queryParameters['created_at__gte'] = (requestParameters['createdAtGte'] as any).toISOString();
        }

        if (requestParameters['createdAtLte'] != null) {
            queryParameters['created_at__lte'] = (requestParameters['createdAtLte'] as any).toISOString();
        }

        if (requestParameters['createdBy'] != null) {
            queryParameters['created_by'] = requestParameters['createdBy'];
        }

        if (requestParameters['modifiedAt'] != null) {
            queryParameters['modified_at'] = (requestParameters['modifiedAt'] as any).toISOString();
        }

        if (requestParameters['modifiedAtGte'] != null) {
            queryParameters['modified_at__gte'] = (requestParameters['modifiedAtGte'] as any).toISOString();
        }

        if (requestParameters['modifiedAtLte'] != null) {
            queryParameters['modified_at__lte'] = (requestParameters['modifiedAtLte'] as any).toISOString();
        }

        if (requestParameters['modifiedBy'] != null) {
            queryParameters['modified_by'] = requestParameters['modifiedBy'];
        }

        if (requestParameters['position'] != null) {
            queryParameters['position'] = requestParameters['position'];
        }

        if (requestParameters['positionGte'] != null) {
            queryParameters['position__gte'] = requestParameters['positionGte'];
        }

        if (requestParameters['positionLte'] != null) {
            queryParameters['position__lte'] = requestParameters['positionLte'];
        }

        if (requestParameters['textbook'] != null) {
            queryParameters['textbook'] = requestParameters['textbook'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_materials/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedCourseMaterialListFromJSON(jsonValue));
    }

    /**
     * Course Materials
     * List
     */
    async contentCourseMaterialsList(requestParameters: ContentCourseMaterialsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedCourseMaterialList> {
        const response = await this.contentCourseMaterialsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Course Materials
     * Partial Update
     */
    async contentCourseMaterialsPartialUpdateRaw(requestParameters: ContentCourseMaterialsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseMaterial>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentCourseMaterialsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_materials/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedCourseMaterialToJSON(requestParameters['patchedCourseMaterial']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseMaterialFromJSON(jsonValue));
    }

    /**
     * Course Materials
     * Partial Update
     */
    async contentCourseMaterialsPartialUpdate(requestParameters: ContentCourseMaterialsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseMaterial> {
        const response = await this.contentCourseMaterialsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Course Materials
     * Retrieve
     */
    async contentCourseMaterialsRetrieveRaw(requestParameters: ContentCourseMaterialsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseMaterial>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentCourseMaterialsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_materials/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseMaterialFromJSON(jsonValue));
    }

    /**
     * Course Materials
     * Retrieve
     */
    async contentCourseMaterialsRetrieve(requestParameters: ContentCourseMaterialsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseMaterial> {
        const response = await this.contentCourseMaterialsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Course Materials
     * Update
     */
    async contentCourseMaterialsUpdateRaw(requestParameters: ContentCourseMaterialsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseMaterial>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentCourseMaterialsUpdate().'
            );
        }

        if (requestParameters['courseMaterial'] == null) {
            throw new runtime.RequiredError(
                'courseMaterial',
                'Required parameter "courseMaterial" was null or undefined when calling contentCourseMaterialsUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_materials/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CourseMaterialToJSON(requestParameters['courseMaterial']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseMaterialFromJSON(jsonValue));
    }

    /**
     * Course Materials
     * Update
     */
    async contentCourseMaterialsUpdate(requestParameters: ContentCourseMaterialsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseMaterial> {
        const response = await this.contentCourseMaterialsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
