/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CourseMaterialPageRange,
  PaginatedCourseMaterialPageRangeList,
  PatchedCourseMaterialPageRange,
} from '../models/index';
import {
    CourseMaterialPageRangeFromJSON,
    CourseMaterialPageRangeToJSON,
    PaginatedCourseMaterialPageRangeListFromJSON,
    PaginatedCourseMaterialPageRangeListToJSON,
    PatchedCourseMaterialPageRangeFromJSON,
    PatchedCourseMaterialPageRangeToJSON,
} from '../models/index';

export interface ContentCourseMaterialPageRangesCreateRequest {
    courseMaterialPageRange: Omit<CourseMaterialPageRange, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentCourseMaterialPageRangesDestroyRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentCourseMaterialPageRangesListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    createdAt?: Date;
    createdAtGte?: Date;
    createdAtLte?: Date;
    createdBy?: string;
    endPage?: string;
    material?: string;
    modifiedAt?: Date;
    modifiedAtGte?: Date;
    modifiedAtLte?: Date;
    modifiedBy?: string;
    position?: number;
    positionGte?: number;
    positionLte?: number;
    startPage?: string;
}

export interface ContentCourseMaterialPageRangesPartialUpdateRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
    patchedCourseMaterialPageRange?: Omit<PatchedCourseMaterialPageRange, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
}

export interface ContentCourseMaterialPageRangesRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentCourseMaterialPageRangesUpdateRequest {
    id: string;
    courseMaterialPageRange: Omit<CourseMaterialPageRange, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class CourseMaterialPageRangesApi extends runtime.BaseAPI {

    /**
     * Course Material Page Ranges
     * Create
     */
    async contentCourseMaterialPageRangesCreateRaw(requestParameters: ContentCourseMaterialPageRangesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseMaterialPageRange>> {
        if (requestParameters['courseMaterialPageRange'] == null) {
            throw new runtime.RequiredError(
                'courseMaterialPageRange',
                'Required parameter "courseMaterialPageRange" was null or undefined when calling contentCourseMaterialPageRangesCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_material_page_ranges/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CourseMaterialPageRangeToJSON(requestParameters['courseMaterialPageRange']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseMaterialPageRangeFromJSON(jsonValue));
    }

    /**
     * Course Material Page Ranges
     * Create
     */
    async contentCourseMaterialPageRangesCreate(requestParameters: ContentCourseMaterialPageRangesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseMaterialPageRange> {
        const response = await this.contentCourseMaterialPageRangesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Course Material Page Ranges
     * Delete
     */
    async contentCourseMaterialPageRangesDestroyRaw(requestParameters: ContentCourseMaterialPageRangesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentCourseMaterialPageRangesDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_material_page_ranges/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Course Material Page Ranges
     * Delete
     */
    async contentCourseMaterialPageRangesDestroy(requestParameters: ContentCourseMaterialPageRangesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.contentCourseMaterialPageRangesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Course Material Page Ranges
     * List
     */
    async contentCourseMaterialPageRangesListRaw(requestParameters: ContentCourseMaterialPageRangesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedCourseMaterialPageRangeList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['created_at'] = (requestParameters['createdAt'] as any).toISOString();
        }

        if (requestParameters['createdAtGte'] != null) {
            queryParameters['created_at__gte'] = (requestParameters['createdAtGte'] as any).toISOString();
        }

        if (requestParameters['createdAtLte'] != null) {
            queryParameters['created_at__lte'] = (requestParameters['createdAtLte'] as any).toISOString();
        }

        if (requestParameters['createdBy'] != null) {
            queryParameters['created_by'] = requestParameters['createdBy'];
        }

        if (requestParameters['endPage'] != null) {
            queryParameters['end_page'] = requestParameters['endPage'];
        }

        if (requestParameters['material'] != null) {
            queryParameters['material'] = requestParameters['material'];
        }

        if (requestParameters['modifiedAt'] != null) {
            queryParameters['modified_at'] = (requestParameters['modifiedAt'] as any).toISOString();
        }

        if (requestParameters['modifiedAtGte'] != null) {
            queryParameters['modified_at__gte'] = (requestParameters['modifiedAtGte'] as any).toISOString();
        }

        if (requestParameters['modifiedAtLte'] != null) {
            queryParameters['modified_at__lte'] = (requestParameters['modifiedAtLte'] as any).toISOString();
        }

        if (requestParameters['modifiedBy'] != null) {
            queryParameters['modified_by'] = requestParameters['modifiedBy'];
        }

        if (requestParameters['position'] != null) {
            queryParameters['position'] = requestParameters['position'];
        }

        if (requestParameters['positionGte'] != null) {
            queryParameters['position__gte'] = requestParameters['positionGte'];
        }

        if (requestParameters['positionLte'] != null) {
            queryParameters['position__lte'] = requestParameters['positionLte'];
        }

        if (requestParameters['startPage'] != null) {
            queryParameters['start_page'] = requestParameters['startPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_material_page_ranges/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedCourseMaterialPageRangeListFromJSON(jsonValue));
    }

    /**
     * Course Material Page Ranges
     * List
     */
    async contentCourseMaterialPageRangesList(requestParameters: ContentCourseMaterialPageRangesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedCourseMaterialPageRangeList> {
        const response = await this.contentCourseMaterialPageRangesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Course Material Page Ranges
     * Partial Update
     */
    async contentCourseMaterialPageRangesPartialUpdateRaw(requestParameters: ContentCourseMaterialPageRangesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseMaterialPageRange>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentCourseMaterialPageRangesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_material_page_ranges/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedCourseMaterialPageRangeToJSON(requestParameters['patchedCourseMaterialPageRange']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseMaterialPageRangeFromJSON(jsonValue));
    }

    /**
     * Course Material Page Ranges
     * Partial Update
     */
    async contentCourseMaterialPageRangesPartialUpdate(requestParameters: ContentCourseMaterialPageRangesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseMaterialPageRange> {
        const response = await this.contentCourseMaterialPageRangesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Course Material Page Ranges
     * Retrieve
     */
    async contentCourseMaterialPageRangesRetrieveRaw(requestParameters: ContentCourseMaterialPageRangesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseMaterialPageRange>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentCourseMaterialPageRangesRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_material_page_ranges/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseMaterialPageRangeFromJSON(jsonValue));
    }

    /**
     * Course Material Page Ranges
     * Retrieve
     */
    async contentCourseMaterialPageRangesRetrieve(requestParameters: ContentCourseMaterialPageRangesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseMaterialPageRange> {
        const response = await this.contentCourseMaterialPageRangesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Course Material Page Ranges
     * Update
     */
    async contentCourseMaterialPageRangesUpdateRaw(requestParameters: ContentCourseMaterialPageRangesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseMaterialPageRange>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentCourseMaterialPageRangesUpdate().'
            );
        }

        if (requestParameters['courseMaterialPageRange'] == null) {
            throw new runtime.RequiredError(
                'courseMaterialPageRange',
                'Required parameter "courseMaterialPageRange" was null or undefined when calling contentCourseMaterialPageRangesUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/course_material_page_ranges/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CourseMaterialPageRangeToJSON(requestParameters['courseMaterialPageRange']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseMaterialPageRangeFromJSON(jsonValue));
    }

    /**
     * Course Material Page Ranges
     * Update
     */
    async contentCourseMaterialPageRangesUpdate(requestParameters: ContentCourseMaterialPageRangesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseMaterialPageRange> {
        const response = await this.contentCourseMaterialPageRangesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
