/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LibraryLink,
  PaginatedLibraryLinkList,
  PatchedLibraryLink,
} from '../models/index';
import {
    LibraryLinkFromJSON,
    LibraryLinkToJSON,
    PaginatedLibraryLinkListFromJSON,
    PaginatedLibraryLinkListToJSON,
    PatchedLibraryLinkFromJSON,
    PatchedLibraryLinkToJSON,
} from '../models/index';

export interface ContentLibraryLinksCreateRequest {
    libraryLink: Omit<LibraryLink, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentLibraryLinksDestroyRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentLibraryLinksListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    course?: string;
    createdAt?: Date;
    createdAtGte?: Date;
    createdAtLte?: Date;
    createdBy?: string;
    group?: string;
    modifiedAt?: Date;
    modifiedAtGte?: Date;
    modifiedAtLte?: Date;
    modifiedBy?: string;
    position?: number;
    positionGte?: number;
    positionLte?: number;
    textbook?: string;
}

export interface ContentLibraryLinksPartialUpdateRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
    patchedLibraryLink?: Omit<PatchedLibraryLink, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
}

export interface ContentLibraryLinksRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentLibraryLinksUpdateRequest {
    id: string;
    libraryLink: Omit<LibraryLink, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class LibraryLinksApi extends runtime.BaseAPI {

    /**
     * Library Links
     * Create
     */
    async contentLibraryLinksCreateRaw(requestParameters: ContentLibraryLinksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LibraryLink>> {
        if (requestParameters['libraryLink'] == null) {
            throw new runtime.RequiredError(
                'libraryLink',
                'Required parameter "libraryLink" was null or undefined when calling contentLibraryLinksCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/library_links/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LibraryLinkToJSON(requestParameters['libraryLink']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LibraryLinkFromJSON(jsonValue));
    }

    /**
     * Library Links
     * Create
     */
    async contentLibraryLinksCreate(requestParameters: ContentLibraryLinksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LibraryLink> {
        const response = await this.contentLibraryLinksCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Library Links
     * Delete
     */
    async contentLibraryLinksDestroyRaw(requestParameters: ContentLibraryLinksDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentLibraryLinksDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/library_links/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Library Links
     * Delete
     */
    async contentLibraryLinksDestroy(requestParameters: ContentLibraryLinksDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.contentLibraryLinksDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Library Links
     * List
     */
    async contentLibraryLinksListRaw(requestParameters: ContentLibraryLinksListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedLibraryLinkList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['course'] != null) {
            queryParameters['course'] = requestParameters['course'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['created_at'] = (requestParameters['createdAt'] as any).toISOString();
        }

        if (requestParameters['createdAtGte'] != null) {
            queryParameters['created_at__gte'] = (requestParameters['createdAtGte'] as any).toISOString();
        }

        if (requestParameters['createdAtLte'] != null) {
            queryParameters['created_at__lte'] = (requestParameters['createdAtLte'] as any).toISOString();
        }

        if (requestParameters['createdBy'] != null) {
            queryParameters['created_by'] = requestParameters['createdBy'];
        }

        if (requestParameters['group'] != null) {
            queryParameters['group'] = requestParameters['group'];
        }

        if (requestParameters['modifiedAt'] != null) {
            queryParameters['modified_at'] = (requestParameters['modifiedAt'] as any).toISOString();
        }

        if (requestParameters['modifiedAtGte'] != null) {
            queryParameters['modified_at__gte'] = (requestParameters['modifiedAtGte'] as any).toISOString();
        }

        if (requestParameters['modifiedAtLte'] != null) {
            queryParameters['modified_at__lte'] = (requestParameters['modifiedAtLte'] as any).toISOString();
        }

        if (requestParameters['modifiedBy'] != null) {
            queryParameters['modified_by'] = requestParameters['modifiedBy'];
        }

        if (requestParameters['position'] != null) {
            queryParameters['position'] = requestParameters['position'];
        }

        if (requestParameters['positionGte'] != null) {
            queryParameters['position__gte'] = requestParameters['positionGte'];
        }

        if (requestParameters['positionLte'] != null) {
            queryParameters['position__lte'] = requestParameters['positionLte'];
        }

        if (requestParameters['textbook'] != null) {
            queryParameters['textbook'] = requestParameters['textbook'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/library_links/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedLibraryLinkListFromJSON(jsonValue));
    }

    /**
     * Library Links
     * List
     */
    async contentLibraryLinksList(requestParameters: ContentLibraryLinksListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedLibraryLinkList> {
        const response = await this.contentLibraryLinksListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Library Links
     * Partial Update
     */
    async contentLibraryLinksPartialUpdateRaw(requestParameters: ContentLibraryLinksPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LibraryLink>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentLibraryLinksPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/library_links/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedLibraryLinkToJSON(requestParameters['patchedLibraryLink']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LibraryLinkFromJSON(jsonValue));
    }

    /**
     * Library Links
     * Partial Update
     */
    async contentLibraryLinksPartialUpdate(requestParameters: ContentLibraryLinksPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LibraryLink> {
        const response = await this.contentLibraryLinksPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Library Links
     * Retrieve
     */
    async contentLibraryLinksRetrieveRaw(requestParameters: ContentLibraryLinksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LibraryLink>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentLibraryLinksRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/library_links/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LibraryLinkFromJSON(jsonValue));
    }

    /**
     * Library Links
     * Retrieve
     */
    async contentLibraryLinksRetrieve(requestParameters: ContentLibraryLinksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LibraryLink> {
        const response = await this.contentLibraryLinksRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Library Links
     * Update
     */
    async contentLibraryLinksUpdateRaw(requestParameters: ContentLibraryLinksUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LibraryLink>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentLibraryLinksUpdate().'
            );
        }

        if (requestParameters['libraryLink'] == null) {
            throw new runtime.RequiredError(
                'libraryLink',
                'Required parameter "libraryLink" was null or undefined when calling contentLibraryLinksUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/library_links/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LibraryLinkToJSON(requestParameters['libraryLink']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LibraryLinkFromJSON(jsonValue));
    }

    /**
     * Library Links
     * Update
     */
    async contentLibraryLinksUpdate(requestParameters: ContentLibraryLinksUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LibraryLink> {
        const response = await this.contentLibraryLinksUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
