/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedTextbookList,
  PatchedTextbook,
  Textbook,
} from '../models/index';
import {
    PaginatedTextbookListFromJSON,
    PaginatedTextbookListToJSON,
    PatchedTextbookFromJSON,
    PatchedTextbookToJSON,
    TextbookFromJSON,
    TextbookToJSON,
} from '../models/index';

export interface ContentTextbooksCreateRequest {
    textbook: Omit<Textbook, 'id'|'pages'|'used_in_courses'|'library_links'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentTextbooksDestroyRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentTextbooksListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    createdAt?: Date;
    createdAtGte?: Date;
    createdAtLte?: Date;
    createdBy?: string;
    group?: string;
    modifiedAt?: Date;
    modifiedAtGte?: Date;
    modifiedAtLte?: Date;
    modifiedBy?: string;
    name?: string;
    position?: number;
    positionGte?: number;
    positionLte?: number;
    slug?: string;
}

export interface ContentTextbooksPartialUpdateRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
    patchedTextbook?: Omit<PatchedTextbook, 'id'|'pages'|'used_in_courses'|'library_links'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
}

export interface ContentTextbooksRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentTextbooksUpdateRequest {
    id: string;
    textbook: Omit<Textbook, 'id'|'pages'|'used_in_courses'|'library_links'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class TextbooksApi extends runtime.BaseAPI {

    /**
     * Textbooks
     * Create
     */
    async contentTextbooksCreateRaw(requestParameters: ContentTextbooksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Textbook>> {
        if (requestParameters['textbook'] == null) {
            throw new runtime.RequiredError(
                'textbook',
                'Required parameter "textbook" was null or undefined when calling contentTextbooksCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbooks/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TextbookToJSON(requestParameters['textbook']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TextbookFromJSON(jsonValue));
    }

    /**
     * Textbooks
     * Create
     */
    async contentTextbooksCreate(requestParameters: ContentTextbooksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Textbook> {
        const response = await this.contentTextbooksCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Textbooks
     * Delete
     */
    async contentTextbooksDestroyRaw(requestParameters: ContentTextbooksDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentTextbooksDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbooks/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Textbooks
     * Delete
     */
    async contentTextbooksDestroy(requestParameters: ContentTextbooksDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.contentTextbooksDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Textbooks
     * List
     */
    async contentTextbooksListRaw(requestParameters: ContentTextbooksListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTextbookList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['created_at'] = (requestParameters['createdAt'] as any).toISOString();
        }

        if (requestParameters['createdAtGte'] != null) {
            queryParameters['created_at__gte'] = (requestParameters['createdAtGte'] as any).toISOString();
        }

        if (requestParameters['createdAtLte'] != null) {
            queryParameters['created_at__lte'] = (requestParameters['createdAtLte'] as any).toISOString();
        }

        if (requestParameters['createdBy'] != null) {
            queryParameters['created_by'] = requestParameters['createdBy'];
        }

        if (requestParameters['group'] != null) {
            queryParameters['group'] = requestParameters['group'];
        }

        if (requestParameters['modifiedAt'] != null) {
            queryParameters['modified_at'] = (requestParameters['modifiedAt'] as any).toISOString();
        }

        if (requestParameters['modifiedAtGte'] != null) {
            queryParameters['modified_at__gte'] = (requestParameters['modifiedAtGte'] as any).toISOString();
        }

        if (requestParameters['modifiedAtLte'] != null) {
            queryParameters['modified_at__lte'] = (requestParameters['modifiedAtLte'] as any).toISOString();
        }

        if (requestParameters['modifiedBy'] != null) {
            queryParameters['modified_by'] = requestParameters['modifiedBy'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['position'] != null) {
            queryParameters['position'] = requestParameters['position'];
        }

        if (requestParameters['positionGte'] != null) {
            queryParameters['position__gte'] = requestParameters['positionGte'];
        }

        if (requestParameters['positionLte'] != null) {
            queryParameters['position__lte'] = requestParameters['positionLte'];
        }

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbooks/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTextbookListFromJSON(jsonValue));
    }

    /**
     * Textbooks
     * List
     */
    async contentTextbooksList(requestParameters: ContentTextbooksListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTextbookList> {
        const response = await this.contentTextbooksListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Textbooks
     * Partial Update
     */
    async contentTextbooksPartialUpdateRaw(requestParameters: ContentTextbooksPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Textbook>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentTextbooksPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbooks/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedTextbookToJSON(requestParameters['patchedTextbook']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TextbookFromJSON(jsonValue));
    }

    /**
     * Textbooks
     * Partial Update
     */
    async contentTextbooksPartialUpdate(requestParameters: ContentTextbooksPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Textbook> {
        const response = await this.contentTextbooksPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Textbooks
     * Retrieve
     */
    async contentTextbooksRetrieveRaw(requestParameters: ContentTextbooksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Textbook>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentTextbooksRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbooks/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TextbookFromJSON(jsonValue));
    }

    /**
     * Textbooks
     * Retrieve
     */
    async contentTextbooksRetrieve(requestParameters: ContentTextbooksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Textbook> {
        const response = await this.contentTextbooksRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Textbooks
     * Update
     */
    async contentTextbooksUpdateRaw(requestParameters: ContentTextbooksUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Textbook>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentTextbooksUpdate().'
            );
        }

        if (requestParameters['textbook'] == null) {
            throw new runtime.RequiredError(
                'textbook',
                'Required parameter "textbook" was null or undefined when calling contentTextbooksUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbooks/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TextbookToJSON(requestParameters['textbook']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TextbookFromJSON(jsonValue));
    }

    /**
     * Textbooks
     * Update
     */
    async contentTextbooksUpdate(requestParameters: ContentTextbooksUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Textbook> {
        const response = await this.contentTextbooksUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
