/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedTextbookPageList,
  PatchedTextbookPage,
  TextbookPage,
} from '../models/index';
import {
    PaginatedTextbookPageListFromJSON,
    PaginatedTextbookPageListToJSON,
    PatchedTextbookPageFromJSON,
    PatchedTextbookPageToJSON,
    TextbookPageFromJSON,
    TextbookPageToJSON,
} from '../models/index';

export interface ContentTextbookPagesCreateRequest {
    textbookPage: Omit<TextbookPage, 'id'|'children'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentTextbookPagesDestroyRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentTextbookPagesListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    createdAt?: Date;
    createdAtGte?: Date;
    createdAtLte?: Date;
    createdBy?: string;
    modifiedAt?: Date;
    modifiedAtGte?: Date;
    modifiedAtLte?: Date;
    modifiedBy?: string;
    name?: string;
    parent?: string;
    position?: number;
    positionGte?: number;
    positionLte?: number;
    textbook?: string;
}

export interface ContentTextbookPagesPartialUpdateRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
    patchedTextbookPage?: Omit<PatchedTextbookPage, 'id'|'children'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
}

export interface ContentTextbookPagesRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface ContentTextbookPagesUpdateRequest {
    id: string;
    textbookPage: Omit<TextbookPage, 'id'|'children'|'created_by'|'created_at'|'modified_by'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class TextbookPagesApi extends runtime.BaseAPI {

    /**
     * Textbook Pages
     * Create
     */
    async contentTextbookPagesCreateRaw(requestParameters: ContentTextbookPagesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TextbookPage>> {
        if (requestParameters['textbookPage'] == null) {
            throw new runtime.RequiredError(
                'textbookPage',
                'Required parameter "textbookPage" was null or undefined when calling contentTextbookPagesCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbook_pages/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TextbookPageToJSON(requestParameters['textbookPage']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TextbookPageFromJSON(jsonValue));
    }

    /**
     * Textbook Pages
     * Create
     */
    async contentTextbookPagesCreate(requestParameters: ContentTextbookPagesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TextbookPage> {
        const response = await this.contentTextbookPagesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Textbook Pages
     * Delete
     */
    async contentTextbookPagesDestroyRaw(requestParameters: ContentTextbookPagesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentTextbookPagesDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbook_pages/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Textbook Pages
     * Delete
     */
    async contentTextbookPagesDestroy(requestParameters: ContentTextbookPagesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.contentTextbookPagesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Textbook Pages
     * List
     */
    async contentTextbookPagesListRaw(requestParameters: ContentTextbookPagesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTextbookPageList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['created_at'] = (requestParameters['createdAt'] as any).toISOString();
        }

        if (requestParameters['createdAtGte'] != null) {
            queryParameters['created_at__gte'] = (requestParameters['createdAtGte'] as any).toISOString();
        }

        if (requestParameters['createdAtLte'] != null) {
            queryParameters['created_at__lte'] = (requestParameters['createdAtLte'] as any).toISOString();
        }

        if (requestParameters['createdBy'] != null) {
            queryParameters['created_by'] = requestParameters['createdBy'];
        }

        if (requestParameters['modifiedAt'] != null) {
            queryParameters['modified_at'] = (requestParameters['modifiedAt'] as any).toISOString();
        }

        if (requestParameters['modifiedAtGte'] != null) {
            queryParameters['modified_at__gte'] = (requestParameters['modifiedAtGte'] as any).toISOString();
        }

        if (requestParameters['modifiedAtLte'] != null) {
            queryParameters['modified_at__lte'] = (requestParameters['modifiedAtLte'] as any).toISOString();
        }

        if (requestParameters['modifiedBy'] != null) {
            queryParameters['modified_by'] = requestParameters['modifiedBy'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['parent'] != null) {
            queryParameters['parent'] = requestParameters['parent'];
        }

        if (requestParameters['position'] != null) {
            queryParameters['position'] = requestParameters['position'];
        }

        if (requestParameters['positionGte'] != null) {
            queryParameters['position__gte'] = requestParameters['positionGte'];
        }

        if (requestParameters['positionLte'] != null) {
            queryParameters['position__lte'] = requestParameters['positionLte'];
        }

        if (requestParameters['textbook'] != null) {
            queryParameters['textbook'] = requestParameters['textbook'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbook_pages/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTextbookPageListFromJSON(jsonValue));
    }

    /**
     * Textbook Pages
     * List
     */
    async contentTextbookPagesList(requestParameters: ContentTextbookPagesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTextbookPageList> {
        const response = await this.contentTextbookPagesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Textbook Pages
     * Partial Update
     */
    async contentTextbookPagesPartialUpdateRaw(requestParameters: ContentTextbookPagesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TextbookPage>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentTextbookPagesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbook_pages/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedTextbookPageToJSON(requestParameters['patchedTextbookPage']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TextbookPageFromJSON(jsonValue));
    }

    /**
     * Textbook Pages
     * Partial Update
     */
    async contentTextbookPagesPartialUpdate(requestParameters: ContentTextbookPagesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TextbookPage> {
        const response = await this.contentTextbookPagesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Textbook Pages
     * Retrieve
     */
    async contentTextbookPagesRetrieveRaw(requestParameters: ContentTextbookPagesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TextbookPage>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentTextbookPagesRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbook_pages/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TextbookPageFromJSON(jsonValue));
    }

    /**
     * Textbook Pages
     * Retrieve
     */
    async contentTextbookPagesRetrieve(requestParameters: ContentTextbookPagesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TextbookPage> {
        const response = await this.contentTextbookPagesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Textbook Pages
     * Update
     */
    async contentTextbookPagesUpdateRaw(requestParameters: ContentTextbookPagesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TextbookPage>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling contentTextbookPagesUpdate().'
            );
        }

        if (requestParameters['textbookPage'] == null) {
            throw new runtime.RequiredError(
                'textbookPage',
                'Required parameter "textbookPage" was null or undefined when calling contentTextbookPagesUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/content/textbook_pages/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TextbookPageToJSON(requestParameters['textbookPage']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TextbookPageFromJSON(jsonValue));
    }

    /**
     * Textbook Pages
     * Update
     */
    async contentTextbookPagesUpdate(requestParameters: ContentTextbookPagesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TextbookPage> {
        const response = await this.contentTextbookPagesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
