version: 2

build:
    os: ubuntu-lts-latest
    tools:
        python: latest
    jobs:
        # Poetry requires special attention here, so that the dependencies are
        # actually installed into the automatically created Python environment.
        install:
            - . $READTHEDOCS_VIRTUALENV_PATH/bin/activate;
              pip install poetry;
              poetry config virtualenvs.create false;
              poetry install --no-interaction --with docs

sphinx:
    configuration: docs/conf.py

formats:
  - pdf
  - epub
