# Generated by Django 6.0.3 on 2026-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openbook_auth", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupgroupassignment",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="openbook_auth.group"
            ),
        ),
        migrations.AddField(
            model_name="signupgroupassignment",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="BE CAREFUL: Allows the user to login to the admin site!",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="signupgroupassignment",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="BE CAREFUL: Makes the user have all permissions without explicitly assigning them!",
                verbose_name="superuser status",
            ),
        ),
    ]
