# Generated by Django 6.0.4 on 2026-05-11 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("openbook_content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "text_format",
                    models.CharField(
                        choices=[
                            ("TEXT", "Plain Text"),
                            ("HTML", "HTML"),
                            ("MD", "Markdown"),
                        ],
                        default="MD",
                        max_length=10,
                        verbose_name="Text Format",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The owner always has full permissions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="openbook_content.librarygroup",
                        verbose_name="Parent Group",
                    ),
                ),
                (
                    "public_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions available to logged-out users and all logged-in users independent of their role.",
                        related_name="+",
                        to="auth.permission",
                        verbose_name="Public Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library Group",
                "verbose_name_plural": "Library Groups",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="course",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="openbook_content.librarygroup",
                verbose_name="Library Group",
            ),
        ),
        migrations.CreateModel(
            name="Textbook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "text_format",
                    models.CharField(
                        choices=[
                            ("TEXT", "Plain Text"),
                            ("HTML", "HTML"),
                            ("MD", "Markdown"),
                        ],
                        default="MD",
                        max_length=10,
                        verbose_name="Text Format",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="textbooks",
                        to="openbook_content.librarygroup",
                        verbose_name="Library Group",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Textbook",
                "verbose_name_plural": "Textbooks",
            },
        ),
        migrations.CreateModel(
            name="LibraryLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified At"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sort order inside the group.",
                        verbose_name="Position",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_links",
                        to="openbook_content.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="openbook_content.librarygroup",
                        verbose_name="Library Group",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "textbook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_links",
                        to="openbook_content.textbook",
                        verbose_name="Textbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library Link",
                "verbose_name_plural": "Library Links",
                "ordering": ("group", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="TextbookPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "text_format",
                    models.CharField(
                        choices=[
                            ("TEXT", "Plain Text"),
                            ("HTML", "HTML"),
                            ("MD", "Markdown"),
                        ],
                        default="MD",
                        max_length=10,
                        verbose_name="Text Format",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position among siblings in ascending order.",
                        verbose_name="Position",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="DOM-like content tree with text and interactive components.",
                        verbose_name="Content Tree",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="openbook_content.textbookpage",
                        verbose_name="Parent Page",
                    ),
                ),
                (
                    "textbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="openbook_content.textbook",
                        verbose_name="Textbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Textbook Page",
                "verbose_name_plural": "Textbook Pages",
                "ordering": ("textbook", "parent", "position", "name"),
            },
        ),
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified At"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Reading order index inside the course syllabus.",
                        verbose_name="Position",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="openbook_content.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "textbook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_courses",
                        to="openbook_content.textbook",
                        verbose_name="Textbook",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_courses",
                        to="openbook_content.textbookpage",
                        verbose_name="Textbook Page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Material",
                "verbose_name_plural": "Course Materials",
                "ordering": ("course", "position"),
            },
        ),
        migrations.AddIndex(
            model_name="librarygroup",
            index=models.Index(
                fields=["parent", "name"], name="openbook_co_parent__aed4ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="librarygroup",
            index=models.Index(
                fields=["parent", "slug"], name="openbook_co_parent__ce8228_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="librarygroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "slug"),
                name="openbook_content_unique_library_group_slug_in_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="librarygroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("slug",),
                name="openbook_content_unique_library_group_slug_root",
            ),
        ),
        migrations.AddIndex(
            model_name="librarylink",
            index=models.Index(
                fields=["group", "position"], name="openbook_co_group_i_f32554_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="librarylink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("course__isnull", False), ("textbook__isnull", True)),
                    models.Q(("course__isnull", True), ("textbook__isnull", False)),
                    _connector="OR",
                ),
                name="openbook_content_library_link_single_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="librarylink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("course__isnull", False)),
                fields=("group", "course"),
                name="openbook_content_unique_group_course_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="librarylink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("textbook__isnull", False)),
                fields=("group", "textbook"),
                name="openbook_content_unique_group_textbook_link",
            ),
        ),
        migrations.AddIndex(
            model_name="textbookpage",
            index=models.Index(
                fields=["textbook", "parent", "position"],
                name="openbook_co_textboo_33c1bf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="textbookpage",
            constraint=models.UniqueConstraint(
                fields=("textbook", "parent", "position"),
                name="openbook_content_unique_page_position_within_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="coursematerial",
            index=models.Index(
                fields=["course", "position"], name="openbook_co_course__e95bbd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursematerial",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("textbook__isnull", False), ("page__isnull", True)),
                    models.Q(("textbook__isnull", True), ("page__isnull", False)),
                    _connector="OR",
                ),
                name="openbook_content_course_material_single_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursematerial",
            constraint=models.UniqueConstraint(
                fields=("course", "position"),
                name="openbook_content_unique_course_material_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursematerial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("textbook__isnull", False)),
                fields=("course", "textbook"),
                name="openbook_content_unique_course_textbook_material",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursematerial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page__isnull", False)),
                fields=("course", "page"),
                name="openbook_content_unique_course_page_material",
            ),
        ),
    ]
