# Generated by Django 6.0.4 on 2026-05-11 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("openbook_content", "0002_librarygroup_course_group_textbook_librarylink_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterialPageRange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified At"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the selected ranges within one syllabus item.",
                        verbose_name="Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Material Page Range",
                "verbose_name_plural": "Course Material Page Ranges",
                "ordering": ("material", "position", "id"),
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("group", "position", "name"),
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="textbook",
            options={
                "ordering": ("group", "position", "name"),
                "verbose_name": "Textbook",
                "verbose_name_plural": "Textbooks",
            },
        ),
        migrations.RemoveConstraint(
            model_name="coursematerial",
            name="openbook_content_course_material_single_target",
        ),
        migrations.RemoveConstraint(
            model_name="coursematerial",
            name="openbook_content_unique_course_textbook_material",
        ),
        migrations.RemoveConstraint(
            model_name="coursematerial",
            name="openbook_content_unique_course_page_material",
        ),
        migrations.AddField(
            model_name="course",
            name="position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Sort order inside the library group.",
                verbose_name="Position",
            ),
        ),
        migrations.AddField(
            model_name="textbook",
            name="position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Sort order inside the library group.",
                verbose_name="Position",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["group", "position"], name="openbook_co_group_i_74e657_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textbook",
            index=models.Index(
                fields=["group", "position"], name="openbook_co_group_i_0e083e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("group", "position"),
                name="openbook_content_unique_course_position_in_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="textbook",
            constraint=models.UniqueConstraint(
                fields=("group", "position"),
                name="openbook_content_unique_textbook_position_in_group",
            ),
        ),
        migrations.AddField(
            model_name="coursematerialpagerange",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="coursematerialpagerange",
            name="end_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_material_range_ends",
                to="openbook_content.textbookpage",
                verbose_name="End Page",
            ),
        ),
        migrations.AddField(
            model_name="coursematerialpagerange",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_ranges",
                to="openbook_content.coursematerial",
                verbose_name="Course Material",
            ),
        ),
        migrations.AddField(
            model_name="coursematerialpagerange",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified By",
            ),
        ),
        migrations.AddField(
            model_name="coursematerialpagerange",
            name="start_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_material_range_starts",
                to="openbook_content.textbookpage",
                verbose_name="Start Page",
            ),
        ),
        migrations.RemoveField(
            model_name="coursematerial",
            name="page",
        ),
        migrations.AddConstraint(
            model_name="coursematerial",
            constraint=models.UniqueConstraint(
                fields=("course", "textbook"),
                name="openbook_content_unique_course_textbook_material",
            ),
        ),
        migrations.AddIndex(
            model_name="coursematerialpagerange",
            index=models.Index(
                fields=["material", "position"], name="openbook_co_materia_6e4902_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursematerialpagerange",
            constraint=models.UniqueConstraint(
                fields=("material", "position"),
                name="openbook_content_unique_material_page_range_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursematerialpagerange",
            constraint=models.UniqueConstraint(
                fields=("material", "start_page", "end_page"),
                name="openbook_content_unique_material_page_range",
            ),
        ),
    ]
