# Generated by Django 6.0.4 on 2026-05-12 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "openbook_content",
            "0004_coursematerialpagerange_alter_course_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("group", "name"),
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="librarylink",
            options={
                "ordering": ("group", "id"),
                "verbose_name": "Library Link",
                "verbose_name_plural": "Library Links",
            },
        ),
        migrations.AlterModelOptions(
            name="textbook",
            options={
                "ordering": ("group", "name"),
                "verbose_name": "Textbook",
                "verbose_name_plural": "Textbooks",
            },
        ),
        migrations.RemoveConstraint(
            model_name="course",
            name="openbook_content_unique_course_position_in_group",
        ),
        migrations.RemoveConstraint(
            model_name="textbook",
            name="openbook_content_unique_textbook_position_in_group",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="openbook_co_group_i_74e657_idx",
        ),
        migrations.RemoveIndex(
            model_name="librarylink",
            name="openbook_co_group_i_f32554_idx",
        ),
        migrations.RemoveIndex(
            model_name="textbook",
            name="openbook_co_group_i_0e083e_idx",
        ),
        migrations.AddIndex(
            model_name="librarylink",
            index=models.Index(fields=["group"], name="openbook_co_group_i_3a053f_idx"),
        ),
        migrations.RemoveField(
            model_name="course",
            name="position",
        ),
        migrations.RemoveField(
            model_name="librarylink",
            name="position",
        ),
        migrations.RemoveField(
            model_name="textbook",
            name="position",
        ),
    ]
