/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface CourseMaterialPageRange
 */
export interface CourseMaterialPageRange {
    /**
     * 
     * @type {string}
     * @memberof CourseMaterialPageRange
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterialPageRange
     */
    material: string;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterialPageRange
     */
    startPage: string;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterialPageRange
     */
    endPage: string;
    /**
     * Order of the selected ranges within one syllabus item.
     * @type {number}
     * @memberof CourseMaterialPageRange
     */
    position?: number;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterialPageRange
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseMaterialPageRange
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterialPageRange
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseMaterialPageRange
     */
    readonly modifiedAt: Date | null;
}

/**
 * Check if a given object implements the CourseMaterialPageRange interface.
 */
export function instanceOfCourseMaterialPageRange(value: object): value is CourseMaterialPageRange {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('material' in value) || value['material'] === undefined) return false;
    if (!('startPage' in value) || value['startPage'] === undefined) return false;
    if (!('endPage' in value) || value['endPage'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function CourseMaterialPageRangeFromJSON(json: any): CourseMaterialPageRange {
    return CourseMaterialPageRangeFromJSONTyped(json, false);
}

export function CourseMaterialPageRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseMaterialPageRange {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'material': json['material'],
        'startPage': json['start_page'],
        'endPage': json['end_page'],
        'position': json['position'] == null ? undefined : json['position'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function CourseMaterialPageRangeToJSON(json: any): CourseMaterialPageRange {
    return CourseMaterialPageRangeToJSONTyped(json, false);
}

export function CourseMaterialPageRangeToJSONTyped(value?: Omit<CourseMaterialPageRange, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'material': value['material'],
        'start_page': value['startPage'],
        'end_page': value['endPage'],
        'position': value['position'],
    };
}

