/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface CourseMaterial
 */
export interface CourseMaterial {
    /**
     * 
     * @type {string}
     * @memberof CourseMaterial
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterial
     */
    course: string;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterial
     */
    textbook?: string | null;
    /**
     * Reading order index inside the course syllabus.
     * @type {number}
     * @memberof CourseMaterial
     */
    position?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourseMaterial
     */
    readonly pageRanges: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterial
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseMaterial
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CourseMaterial
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseMaterial
     */
    readonly modifiedAt: Date | null;
}

/**
 * Check if a given object implements the CourseMaterial interface.
 */
export function instanceOfCourseMaterial(value: object): value is CourseMaterial {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('course' in value) || value['course'] === undefined) return false;
    if (!('pageRanges' in value) || value['pageRanges'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function CourseMaterialFromJSON(json: any): CourseMaterial {
    return CourseMaterialFromJSONTyped(json, false);
}

export function CourseMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseMaterial {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'course': json['course'],
        'textbook': json['textbook'] == null ? undefined : json['textbook'],
        'position': json['position'] == null ? undefined : json['position'],
        'pageRanges': json['page_ranges'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function CourseMaterialToJSON(json: any): CourseMaterial {
    return CourseMaterialToJSONTyped(json, false);
}

export function CourseMaterialToJSONTyped(value?: Omit<CourseMaterial, 'id'|'page_ranges'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'course': value['course'],
        'textbook': value['textbook'],
        'position': value['position'],
    };
}

