/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Provide default scope fields for serializers of models with ScopedRolesMixin.
 * 
 * Use this as a default serializer that adds all scope fields.
 * @export
 * @interface LibraryGroup
 */
export interface LibraryGroup {
    /**
     * 
     * @type {string}
     * @memberof LibraryGroup
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof LibraryGroup
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof LibraryGroup
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LibraryGroup
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof LibraryGroup
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof LibraryGroup
     */
    parent?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibraryGroup
     */
    readonly children: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibraryGroup
     */
    readonly textbooks: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibraryGroup
     */
    readonly courses: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibraryGroup
     */
    readonly links: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof LibraryGroup
     */
    readonly owner: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibraryGroup
     */
    publicPermissions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibraryGroup
     */
    readonly roleAssignments: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibraryGroup
     */
    readonly enrollmentMethods: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibraryGroup
     */
    readonly accessRequests: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof LibraryGroup
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof LibraryGroup
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof LibraryGroup
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof LibraryGroup
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the LibraryGroup interface.
 */
export function instanceOfLibraryGroup(value: object): value is LibraryGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('children' in value) || value['children'] === undefined) return false;
    if (!('textbooks' in value) || value['textbooks'] === undefined) return false;
    if (!('courses' in value) || value['courses'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('publicPermissions' in value) || value['publicPermissions'] === undefined) return false;
    if (!('roleAssignments' in value) || value['roleAssignments'] === undefined) return false;
    if (!('enrollmentMethods' in value) || value['enrollmentMethods'] === undefined) return false;
    if (!('accessRequests' in value) || value['accessRequests'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function LibraryGroupFromJSON(json: any): LibraryGroup {
    return LibraryGroupFromJSONTyped(json, false);
}

export function LibraryGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibraryGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        'children': json['children'],
        'textbooks': json['textbooks'],
        'courses': json['courses'],
        'links': json['links'],
        'owner': json['owner'],
        'publicPermissions': json['public_permissions'],
        'roleAssignments': json['role_assignments'],
        'enrollmentMethods': json['enrollment_methods'],
        'accessRequests': json['access_requests'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function LibraryGroupToJSON(json: any): LibraryGroup {
    return LibraryGroupToJSONTyped(json, false);
}

export function LibraryGroupToJSONTyped(value?: Omit<LibraryGroup, 'id'|'children'|'textbooks'|'courses'|'links'|'owner'|'role_assignments'|'enrollment_methods'|'access_requests'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'parent': value['parent'],
        'public_permissions': value['publicPermissions'],
    };
}

