/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface LibraryLink
 */
export interface LibraryLink {
    /**
     * 
     * @type {string}
     * @memberof LibraryLink
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof LibraryLink
     */
    group: string;
    /**
     * 
     * @type {string}
     * @memberof LibraryLink
     */
    course?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LibraryLink
     */
    textbook?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LibraryLink
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof LibraryLink
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof LibraryLink
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof LibraryLink
     */
    readonly modifiedAt: Date | null;
}

/**
 * Check if a given object implements the LibraryLink interface.
 */
export function instanceOfLibraryLink(value: object): value is LibraryLink {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function LibraryLinkFromJSON(json: any): LibraryLink {
    return LibraryLinkFromJSONTyped(json, false);
}

export function LibraryLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibraryLink {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'group': json['group'],
        'course': json['course'] == null ? undefined : json['course'],
        'textbook': json['textbook'] == null ? undefined : json['textbook'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function LibraryLinkToJSON(json: any): LibraryLink {
    return LibraryLinkToJSONTyped(json, false);
}

export function LibraryLinkToJSONTyped(value?: Omit<LibraryLink, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'course': value['course'],
        'textbook': value['textbook'],
    };
}

