/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LibraryGroup } from './LibraryGroup';
import {
    LibraryGroupFromJSON,
    LibraryGroupFromJSONTyped,
    LibraryGroupToJSON,
    LibraryGroupToJSONTyped,
} from './LibraryGroup';

/**
 * 
 * @export
 * @interface PaginatedLibraryGroupList
 */
export interface PaginatedLibraryGroupList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLibraryGroupList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLibraryGroupList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLibraryGroupList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LibraryGroup>}
     * @memberof PaginatedLibraryGroupList
     */
    results: Array<LibraryGroup>;
}

/**
 * Check if a given object implements the PaginatedLibraryGroupList interface.
 */
export function instanceOfPaginatedLibraryGroupList(value: object): value is PaginatedLibraryGroupList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedLibraryGroupListFromJSON(json: any): PaginatedLibraryGroupList {
    return PaginatedLibraryGroupListFromJSONTyped(json, false);
}

export function PaginatedLibraryGroupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLibraryGroupList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LibraryGroupFromJSON)),
    };
}

export function PaginatedLibraryGroupListToJSON(json: any): PaginatedLibraryGroupList {
    return PaginatedLibraryGroupListToJSONTyped(json, false);
}

export function PaginatedLibraryGroupListToJSONTyped(value?: PaginatedLibraryGroupList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(LibraryGroupToJSON)),
    };
}

