/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LibraryLink } from './LibraryLink';
import {
    LibraryLinkFromJSON,
    LibraryLinkFromJSONTyped,
    LibraryLinkToJSON,
    LibraryLinkToJSONTyped,
} from './LibraryLink';

/**
 * 
 * @export
 * @interface PaginatedLibraryLinkList
 */
export interface PaginatedLibraryLinkList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLibraryLinkList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLibraryLinkList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLibraryLinkList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LibraryLink>}
     * @memberof PaginatedLibraryLinkList
     */
    results: Array<LibraryLink>;
}

/**
 * Check if a given object implements the PaginatedLibraryLinkList interface.
 */
export function instanceOfPaginatedLibraryLinkList(value: object): value is PaginatedLibraryLinkList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedLibraryLinkListFromJSON(json: any): PaginatedLibraryLinkList {
    return PaginatedLibraryLinkListFromJSONTyped(json, false);
}

export function PaginatedLibraryLinkListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLibraryLinkList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LibraryLinkFromJSON)),
    };
}

export function PaginatedLibraryLinkListToJSON(json: any): PaginatedLibraryLinkList {
    return PaginatedLibraryLinkListToJSONTyped(json, false);
}

export function PaginatedLibraryLinkListToJSONTyped(value?: PaginatedLibraryLinkList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(LibraryLinkToJSON)),
    };
}

