/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Textbook } from './Textbook';
import {
    TextbookFromJSON,
    TextbookFromJSONTyped,
    TextbookToJSON,
    TextbookToJSONTyped,
} from './Textbook';

/**
 * 
 * @export
 * @interface PaginatedTextbookList
 */
export interface PaginatedTextbookList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTextbookList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTextbookList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTextbookList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Textbook>}
     * @memberof PaginatedTextbookList
     */
    results: Array<Textbook>;
}

/**
 * Check if a given object implements the PaginatedTextbookList interface.
 */
export function instanceOfPaginatedTextbookList(value: object): value is PaginatedTextbookList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTextbookListFromJSON(json: any): PaginatedTextbookList {
    return PaginatedTextbookListFromJSONTyped(json, false);
}

export function PaginatedTextbookListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTextbookList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TextbookFromJSON)),
    };
}

export function PaginatedTextbookListToJSON(json: any): PaginatedTextbookList {
    return PaginatedTextbookListToJSONTyped(json, false);
}

export function PaginatedTextbookListToJSONTyped(value?: PaginatedTextbookList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TextbookToJSON)),
    };
}

