/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseMaterial } from './CourseMaterial';
import {
    CourseMaterialFromJSON,
    CourseMaterialFromJSONTyped,
    CourseMaterialToJSON,
    CourseMaterialToJSONTyped,
} from './CourseMaterial';

/**
 * 
 * @export
 * @interface PaginatedCourseMaterialList
 */
export interface PaginatedCourseMaterialList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCourseMaterialList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCourseMaterialList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCourseMaterialList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CourseMaterial>}
     * @memberof PaginatedCourseMaterialList
     */
    results: Array<CourseMaterial>;
}

/**
 * Check if a given object implements the PaginatedCourseMaterialList interface.
 */
export function instanceOfPaginatedCourseMaterialList(value: object): value is PaginatedCourseMaterialList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedCourseMaterialListFromJSON(json: any): PaginatedCourseMaterialList {
    return PaginatedCourseMaterialListFromJSONTyped(json, false);
}

export function PaginatedCourseMaterialListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCourseMaterialList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CourseMaterialFromJSON)),
    };
}

export function PaginatedCourseMaterialListToJSON(json: any): PaginatedCourseMaterialList {
    return PaginatedCourseMaterialListToJSONTyped(json, false);
}

export function PaginatedCourseMaterialListToJSONTyped(value?: PaginatedCourseMaterialList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CourseMaterialToJSON)),
    };
}

