/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseMaterialPageRange } from './CourseMaterialPageRange';
import {
    CourseMaterialPageRangeFromJSON,
    CourseMaterialPageRangeFromJSONTyped,
    CourseMaterialPageRangeToJSON,
    CourseMaterialPageRangeToJSONTyped,
} from './CourseMaterialPageRange';

/**
 * 
 * @export
 * @interface PaginatedCourseMaterialPageRangeList
 */
export interface PaginatedCourseMaterialPageRangeList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCourseMaterialPageRangeList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCourseMaterialPageRangeList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCourseMaterialPageRangeList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CourseMaterialPageRange>}
     * @memberof PaginatedCourseMaterialPageRangeList
     */
    results: Array<CourseMaterialPageRange>;
}

/**
 * Check if a given object implements the PaginatedCourseMaterialPageRangeList interface.
 */
export function instanceOfPaginatedCourseMaterialPageRangeList(value: object): value is PaginatedCourseMaterialPageRangeList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedCourseMaterialPageRangeListFromJSON(json: any): PaginatedCourseMaterialPageRangeList {
    return PaginatedCourseMaterialPageRangeListFromJSONTyped(json, false);
}

export function PaginatedCourseMaterialPageRangeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCourseMaterialPageRangeList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CourseMaterialPageRangeFromJSON)),
    };
}

export function PaginatedCourseMaterialPageRangeListToJSON(json: any): PaginatedCourseMaterialPageRangeList {
    return PaginatedCourseMaterialPageRangeListToJSONTyped(json, false);
}

export function PaginatedCourseMaterialPageRangeListToJSONTyped(value?: PaginatedCourseMaterialPageRangeList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CourseMaterialPageRangeToJSON)),
    };
}

