/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextbookPage } from './TextbookPage';
import {
    TextbookPageFromJSON,
    TextbookPageFromJSONTyped,
    TextbookPageToJSON,
    TextbookPageToJSONTyped,
} from './TextbookPage';

/**
 * 
 * @export
 * @interface PaginatedTextbookPageList
 */
export interface PaginatedTextbookPageList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTextbookPageList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTextbookPageList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTextbookPageList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TextbookPage>}
     * @memberof PaginatedTextbookPageList
     */
    results: Array<TextbookPage>;
}

/**
 * Check if a given object implements the PaginatedTextbookPageList interface.
 */
export function instanceOfPaginatedTextbookPageList(value: object): value is PaginatedTextbookPageList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTextbookPageListFromJSON(json: any): PaginatedTextbookPageList {
    return PaginatedTextbookPageListFromJSONTyped(json, false);
}

export function PaginatedTextbookPageListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTextbookPageList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TextbookPageFromJSON)),
    };
}

export function PaginatedTextbookPageListToJSON(json: any): PaginatedTextbookPageList {
    return PaginatedTextbookPageListToJSONTyped(json, false);
}

export function PaginatedTextbookPageListToJSONTyped(value?: PaginatedTextbookPageList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TextbookPageToJSON)),
    };
}

