/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface PatchedCourseMaterial
 */
export interface PatchedCourseMaterial {
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterial
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterial
     */
    course?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterial
     */
    textbook?: string | null;
    /**
     * Reading order index inside the course syllabus.
     * @type {number}
     * @memberof PatchedCourseMaterial
     */
    position?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedCourseMaterial
     */
    readonly pageRanges?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterial
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCourseMaterial
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterial
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCourseMaterial
     */
    readonly modifiedAt?: Date | null;
}

/**
 * Check if a given object implements the PatchedCourseMaterial interface.
 */
export function instanceOfPatchedCourseMaterial(value: object): value is PatchedCourseMaterial {
    return true;
}

export function PatchedCourseMaterialFromJSON(json: any): PatchedCourseMaterial {
    return PatchedCourseMaterialFromJSONTyped(json, false);
}

export function PatchedCourseMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCourseMaterial {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'course': json['course'] == null ? undefined : json['course'],
        'textbook': json['textbook'] == null ? undefined : json['textbook'],
        'position': json['position'] == null ? undefined : json['position'],
        'pageRanges': json['page_ranges'] == null ? undefined : json['page_ranges'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedCourseMaterialToJSON(json: any): PatchedCourseMaterial {
    return PatchedCourseMaterialToJSONTyped(json, false);
}

export function PatchedCourseMaterialToJSONTyped(value?: Omit<PatchedCourseMaterial, 'id'|'page_ranges'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'course': value['course'],
        'textbook': value['textbook'],
        'position': value['position'],
    };
}

