/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface PatchedTextbookPage
 */
export interface PatchedTextbookPage {
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbookPage
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbookPage
     */
    textbook?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbookPage
     */
    parent?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedTextbookPage
     */
    readonly children?: Array<string>;
    /**
     * Position among siblings in ascending order.
     * @type {number}
     * @memberof PatchedTextbookPage
     */
    position?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbookPage
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbookPage
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof PatchedTextbookPage
     */
    textFormat?: TextFormatEnum;
    /**
     * DOM-like content tree with text and interactive components.
     * @type {any}
     * @memberof PatchedTextbookPage
     */
    content?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbookPage
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTextbookPage
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbookPage
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTextbookPage
     */
    readonly modifiedAt?: Date | null;
}



/**
 * Check if a given object implements the PatchedTextbookPage interface.
 */
export function instanceOfPatchedTextbookPage(value: object): value is PatchedTextbookPage {
    return true;
}

export function PatchedTextbookPageFromJSON(json: any): PatchedTextbookPage {
    return PatchedTextbookPageFromJSONTyped(json, false);
}

export function PatchedTextbookPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTextbookPage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'textbook': json['textbook'] == null ? undefined : json['textbook'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'children': json['children'] == null ? undefined : json['children'],
        'position': json['position'] == null ? undefined : json['position'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'content': json['content'] == null ? undefined : json['content'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedTextbookPageToJSON(json: any): PatchedTextbookPage {
    return PatchedTextbookPageToJSONTyped(json, false);
}

export function PatchedTextbookPageToJSONTyped(value?: Omit<PatchedTextbookPage, 'id'|'children'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'textbook': value['textbook'],
        'parent': value['parent'],
        'position': value['position'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'content': value['content'],
    };
}

