/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface PatchedTextbook
 */
export interface PatchedTextbook {
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbook
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbook
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbook
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbook
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof PatchedTextbook
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbook
     */
    group?: string;
    /**
     * Sort order inside the library group.
     * @type {number}
     * @memberof PatchedTextbook
     */
    position?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedTextbook
     */
    readonly pages?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedTextbook
     */
    readonly usedInCourses?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedTextbook
     */
    readonly libraryLinks?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbook
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTextbook
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedTextbook
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTextbook
     */
    readonly modifiedAt?: Date | null;
}



/**
 * Check if a given object implements the PatchedTextbook interface.
 */
export function instanceOfPatchedTextbook(value: object): value is PatchedTextbook {
    return true;
}

export function PatchedTextbookFromJSON(json: any): PatchedTextbook {
    return PatchedTextbookFromJSONTyped(json, false);
}

export function PatchedTextbookFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTextbook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'group': json['group'] == null ? undefined : json['group'],
        'position': json['position'] == null ? undefined : json['position'],
        'pages': json['pages'] == null ? undefined : json['pages'],
        'usedInCourses': json['used_in_courses'] == null ? undefined : json['used_in_courses'],
        'libraryLinks': json['library_links'] == null ? undefined : json['library_links'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedTextbookToJSON(json: any): PatchedTextbook {
    return PatchedTextbookToJSONTyped(json, false);
}

export function PatchedTextbookToJSONTyped(value?: Omit<PatchedTextbook, 'id'|'pages'|'used_in_courses'|'library_links'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'group': value['group'],
        'position': value['position'],
    };
}

