/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface PatchedCourseMaterialPageRange
 */
export interface PatchedCourseMaterialPageRange {
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterialPageRange
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterialPageRange
     */
    material?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterialPageRange
     */
    startPage?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterialPageRange
     */
    endPage?: string;
    /**
     * Order of the selected ranges within one syllabus item.
     * @type {number}
     * @memberof PatchedCourseMaterialPageRange
     */
    position?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterialPageRange
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCourseMaterialPageRange
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedCourseMaterialPageRange
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCourseMaterialPageRange
     */
    readonly modifiedAt?: Date | null;
}

/**
 * Check if a given object implements the PatchedCourseMaterialPageRange interface.
 */
export function instanceOfPatchedCourseMaterialPageRange(value: object): value is PatchedCourseMaterialPageRange {
    return true;
}

export function PatchedCourseMaterialPageRangeFromJSON(json: any): PatchedCourseMaterialPageRange {
    return PatchedCourseMaterialPageRangeFromJSONTyped(json, false);
}

export function PatchedCourseMaterialPageRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCourseMaterialPageRange {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'material': json['material'] == null ? undefined : json['material'],
        'startPage': json['start_page'] == null ? undefined : json['start_page'],
        'endPage': json['end_page'] == null ? undefined : json['end_page'],
        'position': json['position'] == null ? undefined : json['position'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedCourseMaterialPageRangeToJSON(json: any): PatchedCourseMaterialPageRange {
    return PatchedCourseMaterialPageRangeToJSONTyped(json, false);
}

export function PatchedCourseMaterialPageRangeToJSONTyped(value?: Omit<PatchedCourseMaterialPageRange, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'material': value['material'],
        'start_page': value['startPage'],
        'end_page': value['endPage'],
        'position': value['position'],
    };
}

