/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Provide default scope fields for serializers of models with ScopedRolesMixin.
 * 
 * Use this as a default serializer that adds all scope fields.
 * @export
 * @interface PatchedLibraryGroup
 */
export interface PatchedLibraryGroup {
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryGroup
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryGroup
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryGroup
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryGroup
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof PatchedLibraryGroup
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryGroup
     */
    parent?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedLibraryGroup
     */
    readonly children?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedLibraryGroup
     */
    readonly textbooks?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedLibraryGroup
     */
    readonly courses?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedLibraryGroup
     */
    readonly links?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryGroup
     */
    readonly owner?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedLibraryGroup
     */
    publicPermissions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedLibraryGroup
     */
    readonly roleAssignments?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedLibraryGroup
     */
    readonly enrollmentMethods?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedLibraryGroup
     */
    readonly accessRequests?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryGroup
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLibraryGroup
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryGroup
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLibraryGroup
     */
    readonly modifiedAt?: Date | null;
}



/**
 * Check if a given object implements the PatchedLibraryGroup interface.
 */
export function instanceOfPatchedLibraryGroup(value: object): value is PatchedLibraryGroup {
    return true;
}

export function PatchedLibraryGroupFromJSON(json: any): PatchedLibraryGroup {
    return PatchedLibraryGroupFromJSONTyped(json, false);
}

export function PatchedLibraryGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLibraryGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        'children': json['children'] == null ? undefined : json['children'],
        'textbooks': json['textbooks'] == null ? undefined : json['textbooks'],
        'courses': json['courses'] == null ? undefined : json['courses'],
        'links': json['links'] == null ? undefined : json['links'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'publicPermissions': json['public_permissions'] == null ? undefined : json['public_permissions'],
        'roleAssignments': json['role_assignments'] == null ? undefined : json['role_assignments'],
        'enrollmentMethods': json['enrollment_methods'] == null ? undefined : json['enrollment_methods'],
        'accessRequests': json['access_requests'] == null ? undefined : json['access_requests'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedLibraryGroupToJSON(json: any): PatchedLibraryGroup {
    return PatchedLibraryGroupToJSONTyped(json, false);
}

export function PatchedLibraryGroupToJSONTyped(value?: Omit<PatchedLibraryGroup, 'id'|'children'|'textbooks'|'courses'|'links'|'owner'|'role_assignments'|'enrollment_methods'|'access_requests'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'parent': value['parent'],
        'public_permissions': value['publicPermissions'],
    };
}

