/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface PatchedLibraryLink
 */
export interface PatchedLibraryLink {
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryLink
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryLink
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryLink
     */
    course?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryLink
     */
    textbook?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryLink
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLibraryLink
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLibraryLink
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLibraryLink
     */
    readonly modifiedAt?: Date | null;
}

/**
 * Check if a given object implements the PatchedLibraryLink interface.
 */
export function instanceOfPatchedLibraryLink(value: object): value is PatchedLibraryLink {
    return true;
}

export function PatchedLibraryLinkFromJSON(json: any): PatchedLibraryLink {
    return PatchedLibraryLinkFromJSONTyped(json, false);
}

export function PatchedLibraryLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLibraryLink {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'group': json['group'] == null ? undefined : json['group'],
        'course': json['course'] == null ? undefined : json['course'],
        'textbook': json['textbook'] == null ? undefined : json['textbook'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedLibraryLinkToJSON(json: any): PatchedLibraryLink {
    return PatchedLibraryLinkToJSONTyped(json, false);
}

export function PatchedLibraryLinkToJSONTyped(value?: Omit<PatchedLibraryLink, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'course': value['course'],
        'textbook': value['textbook'],
    };
}

