/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface TextbookPage
 */
export interface TextbookPage {
    /**
     * 
     * @type {string}
     * @memberof TextbookPage
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof TextbookPage
     */
    textbook: string;
    /**
     * 
     * @type {string}
     * @memberof TextbookPage
     */
    parent?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TextbookPage
     */
    readonly children: Array<string>;
    /**
     * Position among siblings in ascending order.
     * @type {number}
     * @memberof TextbookPage
     */
    position?: number;
    /**
     * 
     * @type {string}
     * @memberof TextbookPage
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TextbookPage
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof TextbookPage
     */
    textFormat?: TextFormatEnum;
    /**
     * DOM-like content tree with text and interactive components.
     * @type {any}
     * @memberof TextbookPage
     */
    content?: any | null;
    /**
     * 
     * @type {string}
     * @memberof TextbookPage
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof TextbookPage
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TextbookPage
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof TextbookPage
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the TextbookPage interface.
 */
export function instanceOfTextbookPage(value: object): value is TextbookPage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('textbook' in value) || value['textbook'] === undefined) return false;
    if (!('children' in value) || value['children'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function TextbookPageFromJSON(json: any): TextbookPage {
    return TextbookPageFromJSONTyped(json, false);
}

export function TextbookPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextbookPage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'textbook': json['textbook'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'children': json['children'],
        'position': json['position'] == null ? undefined : json['position'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'content': json['content'] == null ? undefined : json['content'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function TextbookPageToJSON(json: any): TextbookPage {
    return TextbookPageToJSONTyped(json, false);
}

export function TextbookPageToJSONTyped(value?: Omit<TextbookPage, 'id'|'children'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'textbook': value['textbook'],
        'parent': value['parent'],
        'position': value['position'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'content': value['content'],
    };
}

