/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface Textbook
 */
export interface Textbook {
    /**
     * 
     * @type {string}
     * @memberof Textbook
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Textbook
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Textbook
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Textbook
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof Textbook
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof Textbook
     */
    group: string;
    /**
     * Sort order inside the library group.
     * @type {number}
     * @memberof Textbook
     */
    position?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Textbook
     */
    readonly pages: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Textbook
     */
    readonly usedInCourses: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Textbook
     */
    readonly libraryLinks: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Textbook
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof Textbook
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Textbook
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof Textbook
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the Textbook interface.
 */
export function instanceOfTextbook(value: object): value is Textbook {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    if (!('usedInCourses' in value) || value['usedInCourses'] === undefined) return false;
    if (!('libraryLinks' in value) || value['libraryLinks'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function TextbookFromJSON(json: any): Textbook {
    return TextbookFromJSONTyped(json, false);
}

export function TextbookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Textbook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'group': json['group'],
        'position': json['position'] == null ? undefined : json['position'],
        'pages': json['pages'],
        'usedInCourses': json['used_in_courses'],
        'libraryLinks': json['library_links'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function TextbookToJSON(json: any): Textbook {
    return TextbookToJSONTyped(json, false);
}

export function TextbookToJSONTyped(value?: Omit<Textbook, 'id'|'pages'|'used_in_courses'|'library_links'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'group': value['group'],
        'position': value['position'],
    };
}

