name: "Bump Dependencies"

on:
    workflow_dispatch:
    schedule:
        - cron: "17 3 * * 1"

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    renovate_minor:
        name: "Bump Dependencies"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  ref: ${{ github.event.repository.default_branch }}

            - name: "Run Renovate"
              uses: renovatebot/github-action@b67590ea780158ccd13192c22a3655a5231f869d # v46.1.8
              with:
                  configurationFile: renovate.json5
                  token: ${{ secrets.RENOVATE_TOKEN }}
              env:
                  LOG_LEVEL: "info"
                  NPM_CONFIG_LEGACY_PEER_DEPS: "true"
                  RENOVATE_GIT_AUTHOR: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
                  RENOVATE_REPOSITORIES: ${{ github.repository }}
