name: "Run Dummy Test Suite"

on:
    workflow_call:

permissions: {}

jobs:
    run-dummy-test-suite:
        name: "Run dummy test suite"
        runs-on: ubuntu-latest

        steps:
            - name: "Report skipped test suite"
              run: |
                echo "No relevant Python/package files changed. Skipping full test suite."
