name: "Run Full Test Suite"

on:
    workflow_call:

permissions:
    contents: read

jobs:
    run-compatibility-matrix:
        name: "Run compatibility matrix (Python ${{ matrix.python-version }})"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.12", "3.13", "3.14"]

        steps:
            - name: "Checkout code"
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  ref: ${{ github.head_ref || github.ref }}

            - name: "Set up CI environment"
              uses: ./.github/actions/setup-ci-environment
              with:
                  setup-python: "true"
                  python-version: ${{ matrix.python-version }}
                  poetry-install-with: ""
                  poetry-install-only: "dev"

            - name: "Run compatibility test matrix"
              run: |
                  npm run test

    run-coverage:
        name: "Run coverage check and code checks"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  ref: ${{ github.head_ref || github.ref }}

            - name: "Set up CI environment"
              uses: ./.github/actions/setup-ci-environment
              with:
                  setup-python: "true"
                  setup-node: "true"

            - name: "Run coverage check"
              run: |
                  export PYTHONPATH=src
                  poetry run coverage run --rcfile=pyproject.toml src/manage.py test tests
                  poetry run coverage report --rcfile=pyproject.toml -m

            - name: "Run code checks"
              run: npm run check
