name: "Run Full Test Suite"

on:
    workflow_call:

permissions:
    contents: read

jobs:
    run-compatibility-matrix:
        name: "Run tests (Python ${{ matrix.python-version }})"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.12", "3.13", "3.14"]

        steps:
            - name: "Checkout code"
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
              with:
                  ref: ${{ github.head_ref || github.ref }}

            - name: "Set up CI environment"
              uses: ./.github/actions/setup-ci-environment
              with:
                  setup-python: "true"
                  python-version: ${{ matrix.python-version }}
                  poetry-install-with: "dev"
                  poetry-install-only: ""

            - name: "Run compatibility test matrix"
              run: npm run test

    code-checks:
        name: "Run code checks"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
              with:
                  ref: ${{ github.head_ref || github.ref }}

            - name: "Set up CI environment"
              uses: ./.github/actions/setup-ci-environment
              with:
                  setup-python: "true"
                  python-version: ${{ matrix.python-version }}
                  poetry-install-with: "dev"
                  poetry-install-only: ""

            - name: "Run code checks"
              run: npm run check
