name: "Run Full Test Suite"

on:
    workflow_call:

permissions:
    contents: read

jobs:
    run-compatibility-matrix:
        name: "Run compatibility matrix (Python ${{ matrix.python-version }})"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.12", "3.13", "3.14"]

        steps:
            - name: "Checkout code"
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  ref: ${{ github.head_ref || github.ref }}

            - name: "Set up CI environment"
              uses: ./.github/actions/setup-ci-environment
              with:
                  setup-python: "true"
                  python-version: ${{ matrix.python-version }}
                  poetry-install-with: "dev"
                  poetry-install-only: ""

            - name: "Run compatibility test matrix"
              run: |
                  npm run test
